INSERT INTO infos (month, day, info) VALUES ('01', '01', 'S. Maria Madre di Dio');
INSERT INTO infos (month, day, info) VALUES ('01', '02', 'S. Basilio, S. Evelina, S. Modesto');
INSERT INTO infos (month, day, info) VALUES ('01', '03', 'S. Genoveffa');
INSERT INTO infos (month, day, info) VALUES ('01', '04', 'S. Fausta, S. Angela, S. Elsa');
INSERT INTO infos (month, day, info) VALUES ('01', '05', 'S. Nazario, S. Amelia');
INSERT INTO infos (month, day, info) VALUES ('01', '06', 'S. Raffaella, S. Melchiorre, S. Baldassarre');
INSERT INTO infos (month, day, info) VALUES ('01', '07', 'S. Luciano');
INSERT INTO infos (month, day, info) VALUES ('01', '08', 'S. Severino');
INSERT INTO infos (month, day, info) VALUES ('01', '09', 'S. Giuliano, S. Alessia, S. Alice');
INSERT INTO infos (month, day, info) VALUES ('01', '10', 'S. Aldo, S. Domiziano, S. Domiziana');
INSERT INTO infos (month, day, info) VALUES ('01', '11', 'S. Igino');
INSERT INTO infos (month, day, info) VALUES ('01', '12', 'S. Probo, S. Tatiana');
INSERT INTO infos (month, day, info) VALUES ('01', '13', 'S. Ilaria, S. Ilario, S. Yvette');
INSERT INTO infos (month, day, info) VALUES ('01', '14', 'S. Benedetta, S. Morena, S. Moreno');
INSERT INTO infos (month, day, info) VALUES ('01', '15', 'S. Mauro, S. Maura, S. Ida');
INSERT INTO infos (month, day, info) VALUES ('01', '16', 'S. Marcello, S. Marcella');
INSERT INTO infos (month, day, info) VALUES ('01', '17', 'S. Antonio, S. Alba, S. Iole');
INSERT INTO infos (month, day, info) VALUES ('01', '18', 'S. Prisca, S. Priscilla, S. Leonardo');
INSERT INTO infos (month, day, info) VALUES ('01', '19', 'S. Mario, S. Pia, S. Pio');
INSERT INTO infos (month, day, info) VALUES ('01', '20', 'S. Sebastiano, S. Fabiano, S. Teodorico');
INSERT INTO infos (month, day, info) VALUES ('01', '21', 'S. Agnese, S. Ines');
INSERT INTO infos (month, day, info) VALUES ('01', '22', 'S. Vincenzo, S. Linda, S. Esmeralda');
INSERT INTO infos (month, day, info) VALUES ('01', '23', 'S. Emerenziana, S. Ramona, S. Armando');
INSERT INTO infos (month, day, info) VALUES ('01', '24', 'S. Francesco, S. Vera, S. Feliciano');
INSERT INTO infos (month, day, info) VALUES ('01', '25', 'S. Savina, S. Savino, S. Sabino');
INSERT INTO infos (month, day, info) VALUES ('01', '26', 'S. Tito e Timoteo, S. Paola');
INSERT INTO infos (month, day, info) VALUES ('01', '27', 'S. Angela, S. Elvira');
INSERT INTO infos (month, day, info) VALUES ('01', '28', 'S. Tommaso, S. Manfredi');
INSERT INTO infos (month, day, info) VALUES ('01', '29', 'S. Gilda, S. Gildo, S. Ciro');
INSERT INTO infos (month, day, info) VALUES ('01', '30', 'S. Giovanni, S. Martina, S. Serenella');
INSERT INTO infos (month, day, info) VALUES ('01', '31', 'S. Giovanni Bosco, S. Marcella, S. Lodovico');
INSERT INTO infos (month, day, info) VALUES ('02', '01', 'S. Brigida, S. Veridiana, S. Brigida');
INSERT INTO infos (month, day, info) VALUES ('02', '02', 'S. Maurizio, S. Sabatina, S. Sabatino');
INSERT INTO infos (month, day, info) VALUES ('02', '03', 'S. Ofelia, S. Oscar');
INSERT INTO infos (month, day, info) VALUES ('02', '04', 'S. Giliberto, S. Biagio');
INSERT INTO infos (month, day, info) VALUES ('02', '05', 'S. Agata');
INSERT INTO infos (month, day, info) VALUES ('02', '06', 'S. Amanda, S. Dorotea, S. Gastone');
INSERT INTO infos (month, day, info) VALUES ('02', '07', 'S. Eugenia');
INSERT INTO infos (month, day, info) VALUES ('02', '08', 'S. Giacomina, S. Jacqueline, S. Onorato');
INSERT INTO infos (month, day, info) VALUES ('02', '09', 'S. Apollonia');
INSERT INTO infos (month, day, info) VALUES ('02', '10', 'S. Guglielmo, S. Wilma, S. Scolastica');
INSERT INTO infos (month, day, info) VALUES ('02', '11', 'S. Eloisia, S. Dante, S. Durante');
INSERT INTO infos (month, day, info) VALUES ('02', '12', 'S. Eulalia, S. Alessio');
INSERT INTO infos (month, day, info) VALUES ('02', '13', 'S. Esmeralda, S. Fosca, S. Maura');
INSERT INTO infos (month, day, info) VALUES ('02', '14', 'S. Valentino, S. Valentina');
INSERT INTO infos (month, day, info) VALUES ('02', '15', 'S. Giorgia, S. Sigfrido');
INSERT INTO infos (month, day, info) VALUES ('02', '16', 'S. Giuliana');
INSERT INTO infos (month, day, info) VALUES ('02', '17', 'S. Marianna, S. Patrizia');
INSERT INTO infos (month, day, info) VALUES ('02', '18', 'S. Cinzia, S. Claudio');
INSERT INTO infos (month, day, info) VALUES ('02', '19', 'S. Corrado, S. Tullio');
INSERT INTO infos (month, day, info) VALUES ('02', '20', 'S. Ulrico, S. Eros');
INSERT INTO infos (month, day, info) VALUES ('02', '21', 'S. Eleonora, S. Nora, S. Pier Damiani');
INSERT INTO infos (month, day, info) VALUES ('02', '22', 'S. Isabella, S. Greta, S. Margherita');
INSERT INTO infos (month, day, info) VALUES ('02', '23', 'S. Livio, S. Romana, S. Tea');
INSERT INTO infos (month, day, info) VALUES ('02', '24', 'S. Edilberto');
INSERT INTO infos (month, day, info) VALUES ('02', '25', 'S. Costanza, S. Romeo');
INSERT INTO infos (month, day, info) VALUES ('02', '26', 'S. Nestore');
INSERT INTO infos (month, day, info) VALUES ('02', '27', 'S. Onorina');
INSERT INTO infos (month, day, info) VALUES ('02', '28', 'Le sacre ceneri, S. Antonietta, S. Erminia');
INSERT INTO infos (month, day, info) VALUES ('03', '01', 'S. Albino, S. Alba, S. Ugo');
INSERT INTO infos (month, day, info) VALUES ('03', '02', 'S. Simplicio, S. Ava, S. Basileo');
INSERT INTO infos (month, day, info) VALUES ('03', '03', 'S. Cunegonda, S. Viola, S. Tiziana');
INSERT INTO infos (month, day, info) VALUES ('03', '04', 'S. Quaresima, S. Casimiro, S. Umberto');
INSERT INTO infos (month, day, info) VALUES ('03', '05', 'S. Foca, S. Adriano, S. Virgilio');
INSERT INTO infos (month, day, info) VALUES ('03', '06', 'S. Marziano, S. Colette, S. Ezio');
INSERT INTO infos (month, day, info) VALUES ('03', '07', 'S. Felicia, S. Augusta, S. Perpetua');
INSERT INTO infos (month, day, info) VALUES ('03', '08', 'S. Giovanni (di Dio), S. Salvatore');
INSERT INTO infos (month, day, info) VALUES ('03', '09', 'S. Francesca');
INSERT INTO infos (month, day, info) VALUES ('03', '10', 'S. Maria Eugenia, S. Gaio, S. Simplicio');
INSERT INTO infos (month, day, info) VALUES ('03', '11', 'S. Costantino');
INSERT INTO infos (month, day, info) VALUES ('03', '12', 'S. Massimiliano, S. Zeno, S. Zenona');
INSERT INTO infos (month, day, info) VALUES ('03', '13', 'S. Rodrigo, S. Eufrasia, S. Letizia');
INSERT INTO infos (month, day, info) VALUES ('03', '14', 'S. Matilde, S. Valeriano, S. Valeriana');
INSERT INTO infos (month, day, info) VALUES ('03', '15', 'S. Cesare, S. Luisa, S. Silvia');
INSERT INTO infos (month, day, info) VALUES ('03', '16', 'S. Eriberto, S. Taziano, S. Taziana');
INSERT INTO infos (month, day, info) VALUES ('03', '17', 'S. Patrizio, S. Patrizia, S. Teodora');
INSERT INTO infos (month, day, info) VALUES ('03', '18', 'S. Cirillo');
INSERT INTO infos (month, day, info) VALUES ('03', '19', 'S. Giuseppe, S. Giuseppina, S. Pino');
INSERT INTO infos (month, day, info) VALUES ('03', '20', 'S. Claudia, S. Alessandra');
INSERT INTO infos (month, day, info) VALUES ('03', '21', 'S. Filemone, S. Benedetta, S. Benedetto');
INSERT INTO infos (month, day, info) VALUES ('03', '22', 'S. Benvenuto, S. Caterina, S. Lavinia');
INSERT INTO infos (month, day, info) VALUES ('03', '23', 'S. Turibio, S. Fedele, S. Nora');
INSERT INTO infos (month, day, info) VALUES ('03', '24', 'S. Gabriele, S. Attilio, S. Romolo');
INSERT INTO infos (month, day, info) VALUES ('03', '25', 'S. Annunziata, S. Nunzia, S. Nunzio');
INSERT INTO infos (month, day, info) VALUES ('03', '26', 'S. Eginardo, S. Emanuele, S. Manuel');
INSERT INTO infos (month, day, info) VALUES ('03', '27', 'S. Augusta, S. Ruperto, S. Romolo');
INSERT INTO infos (month, day, info) VALUES ('03', '28', 'S. Sisto');
INSERT INTO infos (month, day, info) VALUES ('03', '29', 'S. Secondo');
INSERT INTO infos (month, day, info) VALUES ('03', '30', 'S. Amedeo, S. Zosimo');
INSERT INTO infos (month, day, info) VALUES ('03', '31', 'S. Beniamino');
INSERT INTO infos (month, day, info) VALUES ('04', '01', 'Sant''Ugo di Grenoble');
INSERT INTO infos (month, day, info) VALUES ('04', '02', 'San Francesco da Paola');
INSERT INTO infos (month, day, info) VALUES ('04', '03', 'San Riccardo di Chichester');
INSERT INTO infos (month, day, info) VALUES ('04', '04', 'Sant''Isidoro di Siviglia');
INSERT INTO infos (month, day, info) VALUES ('04', '05', 'San Vincenzo Ferrer');
INSERT INTO infos (month, day, info) VALUES ('04', '06', 'San Pietro da Verona');
INSERT INTO infos (month, day, info) VALUES ('04', '07', 'San Giovanni Battista de La Salle');
INSERT INTO infos (month, day, info) VALUES ('04', '08', 'Santa Giulia Billiart');
INSERT INTO infos (month, day, info) VALUES ('04', '09', 'San Demetrio di Tessalonica');
INSERT INTO infos (month, day, info) VALUES ('04', '10', 'San Ezechiele');
INSERT INTO infos (month, day, info) VALUES ('04', '11', 'Santo Stanislao di Cracovia');
INSERT INTO infos (month, day, info) VALUES ('04', '12', 'San Zeno di Verona');
INSERT INTO infos (month, day, info) VALUES ('04', '13', 'San Martino I Papa');
INSERT INTO infos (month, day, info) VALUES ('04', '14', 'San Girolamo di Roma');
INSERT INTO infos (month, day, info) VALUES ('04', '15', 'Santa Teresa di Gesù Bambino');
INSERT INTO infos (month, day, info) VALUES ('04', '16', 'San Bernadette Soubirous');
INSERT INTO infos (month, day, info) VALUES ('04', '17', 'San Anselmo d Aosta');
INSERT INTO infos (month, day, info) VALUES ('04', '18', 'San Galdino');
INSERT INTO infos (month, day, info) VALUES ('04', '19', 'Santa Emma di Gurk');
INSERT INTO infos (month, day, info) VALUES ('04', '20', 'San Teodoro di Amasea');
INSERT INTO infos (month, day, info) VALUES ('04', '21', 'San Anselmo di Canterbury');
INSERT INTO infos (month, day, info) VALUES ('04', '22', 'Santa Maria Maddalena de'' Pazzi');
INSERT INTO infos (month, day, info) VALUES ('04', '23', 'San Giorgio Martire');
INSERT INTO infos (month, day, info) VALUES ('04', '24', 'Santa Fidelia');
INSERT INTO infos (month, day, info) VALUES ('04', '25', 'San Marco Evangelista');
INSERT INTO infos (month, day, info) VALUES ('04', '26', 'San Giovanni Battista Piamarta');
INSERT INTO infos (month, day, info) VALUES ('04', '27', 'Santa Zita');
INSERT INTO infos (month, day, info) VALUES ('04', '28', 'Santa Gianna Beretta Molla');
INSERT INTO infos (month, day, info) VALUES ('04', '29', 'Santa Caterina da Siena');
INSERT INTO infos (month, day, info) VALUES ('04', '30', 'San Pio V Papa');
INSERT INTO infos (month, day, info) VALUES ('05', '01', 'S. Giuseppe, lavoratore');
INSERT INTO infos (month, day, info) VALUES ('05', '02', 'S. Atanasio');
INSERT INTO infos (month, day, info) VALUES ('05', '03', 'S. Filippo, S. Giacomo');
INSERT INTO infos (month, day, info) VALUES ('05', '04', 'S. Agapio, S. Secondino');
INSERT INTO infos (month, day, info) VALUES ('05', '05', 'S. Gioviniano');
INSERT INTO infos (month, day, info) VALUES ('05', '06', 'S. Lucio di Cirene');
INSERT INTO infos (month, day, info) VALUES ('05', '07', 'S. Domitilla');
INSERT INTO infos (month, day, info) VALUES ('05', '08', 'S. Vittore il Moro');
INSERT INTO infos (month, day, info) VALUES ('05', '09', 'Isaia');
INSERT INTO infos (month, day, info) VALUES ('05', '10', 'S. Giobbe');
INSERT INTO infos (month, day, info) VALUES ('05', '11', 'S. Maiulo di Adrumeto');
INSERT INTO infos (month, day, info) VALUES ('05', '12', 'S. Nereo, S. Achilleo');
INSERT INTO infos (month, day, info) VALUES ('05', '13', 'Nostra Signora di Fatima');
INSERT INTO infos (month, day, info) VALUES ('05', '14', 'S. Mattia');
INSERT INTO infos (month, day, info) VALUES ('05', '15', 'S. Isidoro');
INSERT INTO infos (month, day, info) VALUES ('05', '16', 'S. Ubaldo');
INSERT INTO infos (month, day, info) VALUES ('05', '17', 'S. Pasquale Baylon');
INSERT INTO infos (month, day, info) VALUES ('05', '18', 'S. Giovanni I');
INSERT INTO infos (month, day, info) VALUES ('05', '19', 'S. Urbano I');
INSERT INTO infos (month, day, info) VALUES ('05', '20', 'S. Bernardino da Siena');
INSERT INTO infos (month, day, info) VALUES ('05', '21', 'S. Cristoforo Magallanes');
INSERT INTO infos (month, day, info) VALUES ('05', '22', 'Santa Rita da Cascia');
INSERT INTO infos (month, day, info) VALUES ('05', '23', 'S. Desiderio');
INSERT INTO infos (month, day, info) VALUES ('05', '24', 'S. Manlio');
INSERT INTO infos (month, day, info) VALUES ('05', '25', 'S. Beda il Venerabile');
INSERT INTO infos (month, day, info) VALUES ('05', '26', 'S. Filippo Neri');
INSERT INTO infos (month, day, info) VALUES ('05', '27', 'S. Agostino di Canterbury');
INSERT INTO infos (month, day, info) VALUES ('05', '28', 'S. Giovanni I');
INSERT INTO infos (month, day, info) VALUES ('05', '29', 'S. Paolo VI');
INSERT INTO infos (month, day, info) VALUES ('05', '30', 'S. Giovannino');
INSERT INTO infos (month, day, info) VALUES ('05', '31', 'Visitazione della Beata Vergine Maria');
INSERT INTO infos (month, day, info) VALUES ('06', '01', 'S. Giustino');
INSERT INTO infos (month, day, info) VALUES ('06', '02', 'S. Marcellino');
INSERT INTO infos (month, day, info) VALUES ('06', '03', 'S. Carlo e compagni - martiri');
INSERT INTO infos (month, day, info) VALUES ('06', '04', 'S. Quirino vescovo');
INSERT INTO infos (month, day, info) VALUES ('06', '05', 'S. Bonifacio vescovo');
INSERT INTO infos (month, day, info) VALUES ('06', '06', 'S. Norberto vescovo');
INSERT INTO infos (month, day, info) VALUES ('06', '07', 'S. Roberto vescovo');
INSERT INTO infos (month, day, info) VALUES ('06', '08', 'S. Medardo vescovo');
INSERT INTO infos (month, day, info) VALUES ('06', '09', 'S. Efrem, S. Primo');
INSERT INTO infos (month, day, info) VALUES ('06', '10', 'S. Diana, S. Marcella');
INSERT INTO infos (month, day, info) VALUES ('06', '11', 'S. Barnaba');
INSERT INTO infos (month, day, info) VALUES ('06', '12', 'S. Guido, S. Onofrio');
INSERT INTO infos (month, day, info) VALUES ('06', '13', 'S. Antonio da Padova');
INSERT INTO infos (month, day, info) VALUES ('06', '14', 'S. Eliseo, S. Valeria, S. Valerio');
INSERT INTO infos (month, day, info) VALUES ('06', '15', 'S. Germana, S. Enrica, S. Germano');
INSERT INTO infos (month, day, info) VALUES ('06', '16', 'S. Giuditta, S. Aureliano');
INSERT INTO infos (month, day, info) VALUES ('06', '17', 'S. Ranieri, S. Manuele, S. Manuela');
INSERT INTO infos (month, day, info) VALUES ('06', '18', 'S. Marina, S. Marinella');
INSERT INTO infos (month, day, info) VALUES ('06', '19', 'S. Romualdo');
INSERT INTO infos (month, day, info) VALUES ('06', '20', 'S. Consolata, S. Ettore, S. Novato');
INSERT INTO infos (month, day, info) VALUES ('06', '21', 'S. Luigi, S. Marzia');
INSERT INTO infos (month, day, info) VALUES ('06', '22', 'S. Paolino, S. Flavia, S. Flavio');
INSERT INTO infos (month, day, info) VALUES ('06', '23', 'S. Lanfranco, S. Alice');
INSERT INTO infos (month, day, info) VALUES ('06', '24', 'S. Romolo, S. Gabriele, S. Battista');
INSERT INTO infos (month, day, info) VALUES ('06', '25', 'S. Orio, S. Oriella, S. Orietta');
INSERT INTO infos (month, day, info) VALUES ('06', '26', 'S. Rodolfo, S. Elisa, S. Filippo');
INSERT INTO infos (month, day, info) VALUES ('06', '27', 'S. Cirillo, S. Lelio, S. Tosco');
INSERT INTO infos (month, day, info) VALUES ('06', '28', 'S. Ireneo, S. Attilio');
INSERT INTO infos (month, day, info) VALUES ('06', '29', 'S. Pietro, S. Paolo');
INSERT INTO infos (month, day, info) VALUES ('06', '30', 'S. Protomartiri Romani, S. Ernesto');
INSERT INTO infos (month, day, info) VALUES ('07', '01', 'S. Albino, S. Alba, S. Ugo');
INSERT INTO infos (month, day, info) VALUES ('07', '02', 'S. Simplicio, S. Ava, S. Basileo');
INSERT INTO infos (month, day, info) VALUES ('07', '03', 'S. Cunegonda, S. Viola, S. Tiziana');
INSERT INTO infos (month, day, info) VALUES ('07', '04', 'S. Quaresima, S. Casimiro, S. Umberto');
INSERT INTO infos (month, day, info) VALUES ('07', '05', 'S. Foca, S. Adriano, S. Virgilio');
INSERT INTO infos (month, day, info) VALUES ('07', '06', 'S. Marziano, S. Colette, S. Ezio');
INSERT INTO infos (month, day, info) VALUES ('07', '07', 'S. Felicia, S. Augusta, S. Perpetua');
INSERT INTO infos (month, day, info) VALUES ('07', '08', 'S. Giovanni (di Dio), S. Salvatore');
INSERT INTO infos (month, day, info) VALUES ('07', '09', 'S. Francesca');
INSERT INTO infos (month, day, info) VALUES ('07', '10', 'S. Maria Eugenia, S. Gaio, S. Simplicio');
INSERT INTO infos (month, day, info) VALUES ('07', '11', 'S. Costantino');
INSERT INTO infos (month, day, info) VALUES ('07', '12', 'S. Massimiliano, S. Zeno, S. Zenona');
INSERT INTO infos (month, day, info) VALUES ('07', '13', 'S. Rodrigo, S. Eufrasia, S. Letizia');
INSERT INTO infos (month, day, info) VALUES ('07', '14', 'S. Matilde, S. Valeriano, S. Valeriana');
INSERT INTO infos (month, day, info) VALUES ('07', '15', 'S. Cesare, S. Luisa, S. Silvia');
INSERT INTO infos (month, day, info) VALUES ('07', '16', 'S. Eriberto, S. Taziano, S. Taziana');
INSERT INTO infos (month, day, info) VALUES ('07', '17', 'S. Patrizio, S. Patrizia, S. Teodora');
INSERT INTO infos (month, day, info) VALUES ('07', '18', 'S. Cirillo');
INSERT INTO infos (month, day, info) VALUES ('07', '19', 'S. Giuseppe, S. Giuseppina, S. Pino');
INSERT INTO infos (month, day, info) VALUES ('07', '20', 'S. Claudia, S. Alessandra');
INSERT INTO infos (month, day, info) VALUES ('07', '21', 'S. Filemone, S. Benedetta, S. Benedetto');
INSERT INTO infos (month, day, info) VALUES ('07', '22', 'S. Benvenuto, S. Caterina, S. Lavinia');
INSERT INTO infos (month, day, info) VALUES ('07', '23', 'S. Turibio, S. Fedele, S. Nora');
INSERT INTO infos (month, day, info) VALUES ('07', '24', 'S. Gabriele, S. Attilio, S. Romolo');
INSERT INTO infos (month, day, info) VALUES ('07', '25', 'S. Annunziata, S. Nunzia, S. Nunzio');
INSERT INTO infos (month, day, info) VALUES ('07', '26', 'S. Eginardo, S. Emanuele, S. Manuel');
INSERT INTO infos (month, day, info) VALUES ('07', '27', 'S. Augusta, S. Ruperto, S. Romolo');
INSERT INTO infos (month, day, info) VALUES ('07', '28', 'S. Sisto');
INSERT INTO infos (month, day, info) VALUES ('07', '29', 'S. Secondo');
INSERT INTO infos (month, day, info) VALUES ('07', '30', 'S. Amedeo, S. Zosimo');
INSERT INTO infos (month, day, info) VALUES ('07', '31', 'S. Beniamino');
INSERT INTO infos (month, day, info) VALUES ('08', '01', 'S. Alfonso Maria de Liguori');
INSERT INTO infos (month, day, info) VALUES ('08', '02', 'S. Eusebio di Vercelli');
INSERT INTO infos (month, day, info) VALUES ('08', '03', 'S. Martino di Mondragone');
INSERT INTO infos (month, day, info) VALUES ('08', '04', 'S. Giovanni Maria Vianney');
INSERT INTO infos (month, day, info) VALUES ('08', '05', 'Dedicazione della Basilica di Santa Maria Maggiore');
INSERT INTO infos (month, day, info) VALUES ('08', '06', 'Trasfigurazione del Signore');
INSERT INTO infos (month, day, info) VALUES ('08', '07', 'S. Gaetano Thiene');
INSERT INTO infos (month, day, info) VALUES ('08', '08', 'S. Domenico di Guzman');
INSERT INTO infos (month, day, info) VALUES ('08', '09', 'S. Teresa Benedetta della Croce');
INSERT INTO infos (month, day, info) VALUES ('08', '10', 'S. Lorenzo');
INSERT INTO infos (month, day, info) VALUES ('08', '11', 'S. Chiara Assisi');
INSERT INTO infos (month, day, info) VALUES ('08', '12', 'S. Giovanna Francesca Frémiot de Chantal');
INSERT INTO infos (month, day, info) VALUES ('08', '13', 'S. Ponziano e S. Ippolito');
INSERT INTO infos (month, day, info) VALUES ('08', '14', 'S. Massimiliano Maria Kolbe');
INSERT INTO infos (month, day, info) VALUES ('08', '15', 'Assunzione di Maria');
INSERT INTO infos (month, day, info) VALUES ('08', '16', 'S. Stefano Ungheria');
INSERT INTO infos (month, day, info) VALUES ('08', '17', 'S. Ippolito');
INSERT INTO infos (month, day, info) VALUES ('08', '18', 'S. Elena');
INSERT INTO infos (month, day, info) VALUES ('08', '19', 'S. Giovanni Eudes');
INSERT INTO infos (month, day, info) VALUES ('08', '20', 'S. Bernardo');
INSERT INTO infos (month, day, info) VALUES ('08', '21', 'S. Pio X');
INSERT INTO infos (month, day, info) VALUES ('08', '22', 'Beata Vergine Maria Regina');
INSERT INTO infos (month, day, info) VALUES ('08', '23', 'S. Rosa da Lima');
INSERT INTO infos (month, day, info) VALUES ('08', '24', 'S. Bartolomeo');
INSERT INTO infos (month, day, info) VALUES ('08', '25', 'S. Luigi IX');
INSERT INTO infos (month, day, info) VALUES ('08', '26', 'S. Giuseppe Calasanzio');
INSERT INTO infos (month, day, info) VALUES ('08', '27', 'S. Monica');
INSERT INTO infos (month, day, info) VALUES ('08', '28', 'S. Agostino');
INSERT INTO infos (month, day, info) VALUES ('08', '29', 'Martirio di S. Giovanni Battista');
INSERT INTO infos (month, day, info) VALUES ('08', '30', 'S. Giovanni Battista');
INSERT INTO infos (month, day, info) VALUES ('08', '31', 'S. Raimondo Nonnato');
INSERT INTO infos (month, day, info) VALUES ('09', '01', 'S. Egidio, abate');
INSERT INTO infos (month, day, info) VALUES ('09', '02', 'S. Antonino di Apamea, martire');
INSERT INTO infos (month, day, info) VALUES ('09', '03', 'S. Gregorio Magno, papa');
INSERT INTO infos (month, day, info) VALUES ('09', '04', 'S. Rosalia, vergine ed eremita');
INSERT INTO infos (month, day, info) VALUES ('09', '05', 'S. Teresa di Calcutta, vergine e fondatrice');
INSERT INTO infos (month, day, info) VALUES ('09', '06', 'S. Zaccaria, profeta');
INSERT INTO infos (month, day, info) VALUES ('09', '07', 'S. Giovanni da Lodi, vescovo');
INSERT INTO infos (month, day, info) VALUES ('09', '08', 'Natività della Vergine Maria');
INSERT INTO infos (month, day, info) VALUES ('09', '09', 'S. Pietro Claver, missionario');
INSERT INTO infos (month, day, info) VALUES ('09', '10', 'S. Nicodemo, discepolo di Gesù');
INSERT INTO infos (month, day, info) VALUES ('09', '11', 'S. Protaso e Gervasio, martiri');
INSERT INTO infos (month, day, info) VALUES ('09', '12', 'S. Nome di Maria');
INSERT INTO infos (month, day, info) VALUES ('09', '13', 'S. Giovanni Crisostomo, vescovo');
INSERT INTO infos (month, day, info) VALUES ('09', '14', 'Esaltazione della Santa Croce');
INSERT INTO infos (month, day, info) VALUES ('09', '15', 'Nostra Signora delle Dolori');
INSERT INTO infos (month, day, info) VALUES ('09', '16', 'S. Cornelio, papa e Cipriano, vescovo');
INSERT INTO infos (month, day, info) VALUES ('09', '17', 'S. Roberto Bellarmino, cardinale');
INSERT INTO infos (month, day, info) VALUES ('09', '18', 'S. Giuseppe da Copertino, sacerdote');
INSERT INTO infos (month, day, info) VALUES ('09', '19', 'S. Gennaro, vescovo e martire');
INSERT INTO infos (month, day, info) VALUES ('09', '20', 'S. Eustachio, martire');
INSERT INTO infos (month, day, info) VALUES ('09', '21', 'S. Matteo, apostolo ed evangelista');
INSERT INTO infos (month, day, info) VALUES ('09', '22', 'S. Maurizio e compagni, martiri');
INSERT INTO infos (month, day, info) VALUES ('09', '23', 'S. Pio da Pietrelcina, sacerdote');
INSERT INTO infos (month, day, info) VALUES ('09', '24', 'Natività di San Giovanni Battista');
INSERT INTO infos (month, day, info) VALUES ('09', '25', 'S. Cosma e Damiano, martiri');
INSERT INTO infos (month, day, info) VALUES ('09', '26', 'S. Cipriano, vescovo e martire');
INSERT INTO infos (month, day, info) VALUES ('09', '27', 'S. Vincenzo de Paoli, sacerdote');
INSERT INTO infos (month, day, info) VALUES ('09', '28', 'S. Venceslao, martire');
INSERT INTO infos (month, day, info) VALUES ('09', '29', 'S. Michele e tutti gli angeli');
INSERT INTO infos (month, day, info) VALUES ('09', '30', 'S. Girolamo, sacerdote e dottore');
INSERT INTO infos (month, day, info) VALUES ('10', '01', 'S. Teresa del Bambin Gesù, vergine del Carmelo di Lisieux e dottore della Chiesa');
INSERT INTO infos (month, day, info) VALUES ('10', '02', 'Santi Angeli Custodi');
INSERT INTO infos (month, day, info) VALUES ('10', '03', 'S. Dionigi Areopagita, vescovo e martire');
INSERT INTO infos (month, day, info) VALUES ('10', '04', 'S. Francesco Assisi, fondatore dei Frati Minori');
INSERT INTO infos (month, day, info) VALUES ('10', '05', 'S. Maria Faustina Kowalska, vergine');
INSERT INTO infos (month, day, info) VALUES ('10', '06', 'S. Bruno, sacerdote, fondatore dei certosini');
INSERT INTO infos (month, day, info) VALUES ('10', '07', 'Beata Vergine del Rosario');
INSERT INTO infos (month, day, info) VALUES ('10', '08', 'S. Pelagia, vergine e martire');
INSERT INTO infos (month, day, info) VALUES ('10', '09', 'S. Dionigi, primo vescovo di Parigi, e compagni, martiri');
INSERT INTO infos (month, day, info) VALUES ('10', '10', 'S. Daniele Comboni, vescovo e martire');
INSERT INTO infos (month, day, info) VALUES ('10', '11', 'S. Giovanni XXIII, papa');
INSERT INTO infos (month, day, info) VALUES ('10', '12', 'Nostra Signora di Aparecida');
INSERT INTO infos (month, day, info) VALUES ('10', '13', 'S. Serafino da Montegranaro, sacerdote');
INSERT INTO infos (month, day, info) VALUES ('10', '14', 'S. Callisto I, papa e martire');
INSERT INTO infos (month, day, info) VALUES ('10', '15', 'S. Teresa Avila, vergine e dottore della Chiesa');
INSERT INTO infos (month, day, info) VALUES ('10', '16', 'S. Gall, abate');
INSERT INTO infos (month, day, info) VALUES ('10', '17', 'S. Ignazio di Antiochia, vescovo e martire');
INSERT INTO infos (month, day, info) VALUES ('10', '18', 'S. Luca, evangelista');
INSERT INTO infos (month, day, info) VALUES ('10', '19', 'S. Paolo della Croce, sacerdote');
INSERT INTO infos (month, day, info) VALUES ('10', '20', 'S. Cornelio, centurione');
INSERT INTO infos (month, day, info) VALUES ('10', '21', 'S. Orsola e compagne, vergini e martiri');
INSERT INTO infos (month, day, info) VALUES ('10', '22', 'S. Giovanni Paolo II, papa');
INSERT INTO infos (month, day, info) VALUES ('10', '23', 'S. Giovanni da Capestrano, sacerdote');
INSERT INTO infos (month, day, info) VALUES ('10', '24', 'S. Antonio María Claret y Clará, arcivescovo');
INSERT INTO infos (month, day, info) VALUES ('10', '25', 'S. Crispino e Crispiniano, martiri');
INSERT INTO infos (month, day, info) VALUES ('10', '26', 'S. Luciano e Marciano, martiri');
INSERT INTO infos (month, day, info) VALUES ('10', '27', 'S. Evaristo, papa');
INSERT INTO infos (month, day, info) VALUES ('10', '28', 'S. Simone e Giuda, apostoli');
INSERT INTO infos (month, day, info) VALUES ('10', '29', 'S. Feliciano, martire');
INSERT INTO infos (month, day, info) VALUES ('10', '30', 'S. Marciano, martire');
INSERT INTO infos (month, day, info) VALUES ('10', '31', 'S. Epimaco di Pelusio, martire');
INSERT INTO infos (month, day, info) VALUES ('11', '01', 'Tutti i Santi');
INSERT INTO infos (month, day, info) VALUES ('11', '02', 'Commemorazione di tutti i fedeli defunti');
INSERT INTO infos (month, day, info) VALUES ('11', '03', 'S. Martino de Porres, religioso domenicano');
INSERT INTO infos (month, day, info) VALUES ('11', '04', 'S. Carlo Borromeo, vescovo');
INSERT INTO infos (month, day, info) VALUES ('11', '05', 'S. Guido Maria Conforti, vescovo');
INSERT INTO infos (month, day, info) VALUES ('11', '06', 'S. Leonardo, eremita');
INSERT INTO infos (month, day, info) VALUES ('11', '07', 'S. Prosdocimo, primo vescovo di Padova');
INSERT INTO infos (month, day, info) VALUES ('11', '08', 'S. Adeodato I, papa');
INSERT INTO infos (month, day, info) VALUES ('11', '09', 'Dedicazione della Basilica Lateranense');
INSERT INTO infos (month, day, info) VALUES ('11', '10', 'S. Leone I Magno, papa');
INSERT INTO infos (month, day, info) VALUES ('11', '11', 'S. Martino, vescovo di Tours');
INSERT INTO infos (month, day, info) VALUES ('11', '12', 'S. Giosafat Kuncewycz, vescovo e martire');
INSERT INTO infos (month, day, info) VALUES ('11', '13', 'S. Brizio, vescovo di Tours');
INSERT INTO infos (month, day, info) VALUES ('11', '14', 'S. Leone IX, papa');
INSERT INTO infos (month, day, info) VALUES ('11', '15', 'S. Alberto Magno, vescovo e dottore');
INSERT INTO infos (month, day, info) VALUES ('11', '16', 'S. Margherita, regina di Scozia');
INSERT INTO infos (month, day, info) VALUES ('11', '17', 'S. Elisabetta Ungheria');
INSERT INTO infos (month, day, info) VALUES ('11', '18', 'Dedicazione delle basiliche di S. Pietro e S. Paolo');
INSERT INTO infos (month, day, info) VALUES ('11', '19', 'S. Cecilia, vergine e martire');
INSERT INTO infos (month, day, info) VALUES ('11', '20', 'S. Felicita, martire');
INSERT INTO infos (month, day, info) VALUES ('11', '21', 'Presentazione della Beata Vergine Maria');
INSERT INTO infos (month, day, info) VALUES ('11', '22', 'S. Cecilia, vergine e martire');
INSERT INTO infos (month, day, info) VALUES ('11', '23', 'S. Clemente I, papa e martire');
INSERT INTO infos (month, day, info) VALUES ('11', '24', 'S. Andrea Dũng Lạc, sacerdote, e compagni, martiri');
INSERT INTO infos (month, day, info) VALUES ('11', '25', 'Santa Caterina Alessandria, vergine e martire');
INSERT INTO infos (month, day, info) VALUES ('11', '26', 'S. Silvestro Guzzolini, abate');
INSERT INTO infos (month, day, info) VALUES ('11', '27', 'S. Virgilio, vescovo di Salisburgo');
INSERT INTO infos (month, day, info) VALUES ('11', '28', 'S. Giacomo della Marca, sacerdote');
INSERT INTO infos (month, day, info) VALUES ('11', '29', 'S. Saturnino, vescovo e martire');
INSERT INTO infos (month, day, info) VALUES ('11', '30', 'S. Andrea, apostolo');
INSERT INTO infos (month, day, info) VALUES ('12', '01', 'S. Eligio, vescovo');
INSERT INTO infos (month, day, info) VALUES ('12', '02', 'S. Viviana, martire');
INSERT INTO infos (month, day, info) VALUES ('12', '03', 'S. Francesco Saverio, sacerdote e missionario');
INSERT INTO infos (month, day, info) VALUES ('12', '04', 'S. Barbara, vergine e martire');
INSERT INTO infos (month, day, info) VALUES ('12', '05', 'S. Crispina, martire');
INSERT INTO infos (month, day, info) VALUES ('12', '06', 'S. Nicola, vescovo');
INSERT INTO infos (month, day, info) VALUES ('12', '07', 'S. Ambrogio, vescovo e dottore della Chiesa');
INSERT INTO infos (month, day, info) VALUES ('12', '08', 'Immacolata Concezione della Beata Vergine Maria');
INSERT INTO infos (month, day, info) VALUES ('12', '09', 'S. Giovanni Diego Cuauhtlatoatzin, veggente di Guadalupe');
INSERT INTO infos (month, day, info) VALUES ('12', '10', 'Madonna di Loreto');
INSERT INTO infos (month, day, info) VALUES ('12', '11', 'S. Damaso I, papa');
INSERT INTO infos (month, day, info) VALUES ('12', '12', 'Santa Giovanna Francesca di Chantal');
INSERT INTO infos (month, day, info) VALUES ('12', '13', 'S. Lucia, vergine e martire');
INSERT INTO infos (month, day, info) VALUES ('12', '14', 'S. Giovanni della Croce, sacerdote e dottore della Chiesa');
INSERT INTO infos (month, day, info) VALUES ('12', '15', 'S. Maria Crocifissa di Rosa, vergine');
INSERT INTO infos (month, day, info) VALUES ('12', '16', 'Las Posadas, Messico');
INSERT INTO infos (month, day, info) VALUES ('12', '17', 'Daniele e i tre giovani profeti');
INSERT INTO infos (month, day, info) VALUES ('12', '18', 'Santa Maria di Guadalupe, patrona America Latina');
INSERT INTO infos (month, day, info) VALUES ('12', '19', 'Adamo ed Eva, primi genitori');
INSERT INTO infos (month, day, info) VALUES ('12', '20', 'Santa Giovanna di Lestonnac');
INSERT INTO infos (month, day, info) VALUES ('12', '21', 'San Tommaso, apostolo');
INSERT INTO infos (month, day, info) VALUES ('12', '22', 'Santa Maria Vergine di Guadalupe');
INSERT INTO infos (month, day, info) VALUES ('12', '23', 'San Giovanni Evangelista');
INSERT INTO infos (month, day, info) VALUES ('12', '24', 'Vigilia di Natale');
INSERT INTO infos (month, day, info) VALUES ('12', '25', 'Natività di Nostro Signore Gesù Cristo');
INSERT INTO infos (month, day, info) VALUES ('12', '26', 'Santo Stefano, protomartire');
INSERT INTO infos (month, day, info) VALUES ('12', '27', 'San Giovanni Apostolo ed Evangelista');
INSERT INTO infos (month, day, info) VALUES ('12', '28', 'Santi Innocenti, martiri');
INSERT INTO infos (month, day, info) VALUES ('12', '29', 'San Tommaso Becket, arcivescovo e martire');
INSERT INTO infos (month, day, info) VALUES ('12', '30', 'Santi Famiglia di Gesù, Maria e Giuseppe');
INSERT INTO infos (month, day, info) VALUES ('12', '31', 'San Silvestro I, papa');