services:
  publisher:
    image: async-rabbitmq-publisher
    build: async-rabbitmq-publisher
    environment:
      - SPRING_PROFILES_ACTIVE=docker,routed
    depends_on:
      lavinmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512m

  consumer-0:
    image: async-rabbitmq-consumer
    build: async-rabbitmq-consumer
    environment:
      - SPRING_PROFILES_ACTIVE=docker,routed_instance_CREATE
    depends_on:
      lavinmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512m

  consumer-1:
    image: async-rabbitmq-consumer
    build: async-rabbitmq-consumer
    environment:
      - SPRING_PROFILES_ACTIVE=docker,routed_instance_UPDATE
    depends_on:
      lavinmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512m

  consumer-2:
    image: async-rabbitmq-consumer
    build: async-rabbitmq-consumer
    environment:
      - SPRING_PROFILES_ACTIVE=docker,routed_instance_DELETE
    depends_on:
      lavinmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512m

  lavinmq:
    image: cloudamqp/lavinmq:latest
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "lavinmqctl", "status" ]
      interval: 5s
      timeout: 2s
      retries: 60
    deploy:
      resources:
        limits:
          memory: 512m
