server.port: 9001
spring.application.name: datetime-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

app:
  default:
    zone: "Europe/Rome"

---
spring.config.activate.on-profile: docker

server.port: 8080
eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/

