server.port: 7004

spring.application.name: gateway-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: read_only

logging:
  level:
    org.springframework.cloud.gateway: DEBUG



