services:
  order-service:
    build:
      context: order-service
    container_name: order-service
    ports:
      - "9000:9000"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=9000
    depends_on:
      - payment-service
      - inventory-service

  payment-service:
    build:
      context: payment-service
    container_name: payment-service
    ports:
      - "9001:9001"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=9001

  inventory-service:
    build:
      context: inventory-service
    container_name: inventory-service
    ports:
      - "9002:9002"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=9002

  h2-database:
    image: oscarfonts/h2
    container_name: h2-database
    ports:
      - "9092:1521"
    environment:
      - H2_OPTIONS=-ifNotExists -tcpAllowOthers