{
 "title": "Prometheus monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Prometheus ready",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    { "expr": "prometheus_ready", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Process memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true
  },
  {
   "title": "Evidently service (8085) memory bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"evidently_service.:8085\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alertmanager (9093) memory bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"alertmanager.:9093\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Process cpu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Evidently service (8085) cpu seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"evidently_service.:8085\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alertmanager (9093) cpu seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"alertmanager.:9093\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notification",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true
  },
  {
   "title": "Total notification",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "alertmanager_notifications_total{integration=\"slack\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Status code", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Tot Response code 200 to Bento service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "BENTOML_activities_model_request_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate Response code 200 to Bento service (duration seconds)",
   "type": "timeseries",
   "description": "Rate of request (duration seconds) in the last 5 minutes",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(BENTOML_activities_model_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bad status code",
   "type": "bargauge",
   "description": "Rate of status code \"500\" and \"503\" from Alermanager (9093) and Prometheus (9090)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(promhttp_metric_handler_requests_total{code!=\"200\"}[1d])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}