services:
  #conductor:
  #  image: orkesio/orkes-conductor-community-standalone:latest
  #  init: true
  #  ports:
  #    - "8080:8080"
  #    - "5000:5000"
  #  volumes:
  #    - redis:/redis
  #    - postgres:/pgdata
  #  healthcheck:
  #    test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080" ]
  #    interval: 30s
  #    timeout: 10s
  #    retries: 5

  order:
    build: order-service
    ports:
      - "9000:9000"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONDUCTOR_SECURITY_CLIENT_KEY_ID=${CONDUCTOR_SECURITY_CLIENT_KEY_ID}
      - CONDUCTOR_SECURITY_CLIENT_SECRET=${CONDUCTOR_SECURITY_CLIENT_SECRET}
      - CONDUCTOR_SERVER_URL=${CONDUCTOR_SERVER_URL}
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9000/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  payment:
    build: payment-service
    ports:
      - "9001:9001"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONDUCTOR_SECURITY_CLIENT_KEY_ID=${CONDUCTOR_SECURITY_CLIENT_KEY_ID}
      - CONDUCTOR_SECURITY_CLIENT_SECRET=${CONDUCTOR_SECURITY_CLIENT_SECRET}
      - CONDUCTOR_SERVER_URL=${CONDUCTOR_SERVER_URL}
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9001/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  inventory:
    build: inventory-service
    ports:
      - "9002:9002"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONDUCTOR_SECURITY_CLIENT_KEY_ID=${CONDUCTOR_SECURITY_CLIENT_KEY_ID}
      - CONDUCTOR_SECURITY_CLIENT_SECRET=${CONDUCTOR_SECURITY_CLIENT_SECRET}
      - CONDUCTOR_SERVER_URL=${CONDUCTOR_SERVER_URL}
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9002/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
