receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:

connectors:
  spanmetrics:

exporters:
  debug:
    verbosity: detailed

  prometheus:
    endpoint: 0.0.0.0:8889

  #prometheusremotewrite:
  #  endpoint: http://prometheus:9090/api/v1/write

  otlphttp:
    endpoint: http://loki:3100/otlp

  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

service:
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8888

  pipelines:
    logs:
      receivers: [ otlp ]
      exporters: [ otlphttp ]

    traces:
      receivers: [otlp]
      exporters: [otlp/jaeger, spanmetrics]

    # The metrics pipeline receives generated span metrics from 'spanmetrics' connector
    # and pushes to Prometheus exporter, which makes them available for scraping on :8889.
    metrics/spanmetrics:
      receivers: [spanmetrics]
      exporters: [prometheus]

