receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

  postgresql:
    endpoint: postgres:5432
    transport: tcp
    username: user
    password: secret
    databases:
      - jdbc_schema
    collection_interval: 1s
    tls:
      insecure: true

  redis:
    endpoint: "redis:6379"
    collection_interval: 1s

processors:
  batch:

exporters:
  otlphttp:
    logs_endpoint: http://loki:3100/otlp/v1/logs
    metrics_endpoint: http://prometheus:9090/api/v1/otlp/v1/metrics
    traces_endpoint: http://tempo:4318/v1/traces

service:
  pipelines:
    metrics:
      receivers: [ otlp, postgresql, redis ]
      exporters: [ otlphttp ]

    logs:
      receivers: [ otlp ]
      exporters: [ otlphttp ]

    traces:
      receivers: [otlp ]
      exporters: [otlphttp]


