scrape_configs:
  - job_name: 'application'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['eureka:8761', 'datetime:8080', 'datetime-composite:8080' ]

  - job_name: 'infrastructure'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:9090', 'otel-collector:8888', 'otel-collector:8889', 'jaeger:14269' ]