services:
  product-service:
    image: product-service-h2
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      resources:
        limits:
          memory: 512m

  order-service:
    build: order-service
    image: order-service
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      resources:
        limits:
          memory: 512m
