version: '3.7'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  front-tier:
  back-tier:

services:
  evidently_service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - grafana
    volumes:
      - ./datasets:/app/datasets
      - ./parameters:/app/parameters
      - ./metrics_app/templates:/app/metrics_app/templates
      - ./scripts:/app/scripts
    ports:
      - "8085:8085"
    networks:
      - back-tier
      - front-tier

  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/prometheus_rules.yml:/etc/prometheus/prometheus_rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    networks:
      - back-tier
    restart: always

  grafana:
    image: grafana/grafana
    user: "472"
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana_datasources.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
      - ./config/grafana_dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      - ./dashboards:/opt/grafana/dashboards
      - grafana_data:/var/lib/grafana
    networks:
      - back-tier
      - front-tier
    restart: always

  bentoml:
    image: activities_model:${TAG}
    ports:
      - "3005:3005"
    networks:
      - back-tier
    depends_on:
      - grafana

  alertmanager:
    image: prom/alertmanager:v0.23.0
    #restart: unless-stopped
    ports:
      - "9093:9093"
    networks:
      - back-tier
    volumes:
      - ./config/alertmanager.yml:/config/alertmanager.yml
    command: '--config.file=/config/alertmanager.yml --log.level=debug'