server:
  port: 8082

mqtt:
  url: ${MQTT_URL:tcp://localhost:1883}
  username: ${MQTT_USERNAME:}
  password: ${MQTT_PASSWORD:}
  clean-session: ${MQTT_CLEAN_SESSION:true}
  client-id: ${MQTT_CLIENT_ID:subscriber-service}
  default-topic: ${MQTT_DEFAULT_TOPIC:bank/#}

---
spring.config.activate.on-profile: docker

mqtt:
  url: tcp://mosquitto:1883


