{
 "title": "Evidently",
 "description": "monitor from evidently metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Feature metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Quality Distance feature",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:data_quality:quality_stat{feature=\"Distance (km)\", metric=~\"max|min|mean|missing_count|most_common_value|infinite_count\"}",
     "legendFormat": "{{dataset}} - {{metric}}"
    }
   ]
  },
  {
   "title": "Quality Average Speed feature",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:data_quality:quality_stat{feature=\"Average Speed (km/h)\", metric=~\"max|min|mean|missing_count|most_common_value|infinite_count\"}",
     "legendFormat": "{{dataset}} - {{metric}}"
    }
   ]
  },
  {
   "title": "Quality Calories Burned feature",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:data_quality:quality_stat{feature=\"Calories Burned\", metric=~\"infinite_count|max|min|missing_count|mean|most_common_value\"}",
     "legendFormat": "{{dataset}} - {{metric}}"
    }
   ]
  },
  {
   "title": "Quality Climb feature",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:data_quality:quality_stat{feature=\"Climb (m)\", metric=~\"infinite_count|max|min|missing_count|mean|most_common_value\"}",
     "legendFormat": "{{dataset}} - {{metric}}"
    }
   ]
  },
  {
   "title": "Quality Average Heart rate feature",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:data_quality:quality_stat{feature=\"Average Heart rate (tpm)\", metric=~\"infinite_count|max|min|missing_count|mean|most_common_value\"}",
     "legendFormat": "{{dataset}} - {{metric}}"
    }
   ]
  },
  { "title": "Drift values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Dataset Drift",
   "type": "state-timeline",
   "description": "Dataset Drift is detected if at least 50% of features drift at a 0.95 confidence level.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "evidently:data_drift:dataset_drift",
     "legendFormat": "dataset drift"
    }
   ]
  },
  {
   "title": "Total in time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:data_drift:n_drifted_features",
     "legendFormat": "# drifted feature"
    },
    {
     "expr": "evidently:cat_target_drift:drift",
     "legendFormat": "Target drift"
    }
   ]
  },
  {
   "title": "# of features",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:data_drift:n_drifted_features / evidently:data_drift:share_drifted_features",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Share of Drifted Features [%]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "evidently:data_drift:share_drifted_features",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number drifted features",
   "type": "timeseries",
   "description": "Number drifted features of production dataset.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "evidently:data_drift:n_drifted_features",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Target Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "evidently:cat_target_drift:drift",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drift features",
   "type": "timeseries",
   "description": "Drift features.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    { "expr": "evidently:data_drift:value", "legendFormat": "{{feature}}" }
   ]
  },
  { "title": "Feature drift", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Data drift values",
   "type": "bargauge",
   "description": "All tests use a threshold = 0.1 by default.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "evidently:data_drift:value", "legendFormat": "{{feature}}" }
   ]
  },
  {
   "title": "Drift Distance feature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "evidently:data_drift:value{feature=\"Distance (km)\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drift feature Average Speed",
   "type": "timeseries",
   "description": "Drift feature Average Speed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "evidently:data_drift:value{feature=\"Average Speed (km/h)\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drift feature Calories Burned",
   "type": "timeseries",
   "description": "Drift feature Calories Burned.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "evidently:data_drift:value{feature=\"Calories Burned\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drift Climb feature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "evidently:data_drift:value{feature=\"Climb (m)\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drift feature Average Heart rate",
   "type": "timeseries",
   "description": "Drift feature Average Heart rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "evidently:data_drift:value{feature=\"Average Heart rate (tpm)\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Rows datasets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "# rows current & reference datasets",
   "type": "timeseries",
   "description": "Count of rows of current and reference datasets.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "evidently:cat_target_drift:count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NOW - Missing and infinite values",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(evidently:data_quality:quality_stat{metric=~\"missing_count\"})",
     "legendFormat": "Number of missing values"
    },
    {
     "expr": "sum(evidently:data_quality:quality_stat{metric=\"infinite_count\"})",
     "legendFormat": "Number of infinite values"
    }
   ]
  },
  { "title": "Correlations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "Features Correlations with Target",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "evidently:num_target_drift:current_correlations{kind=\"target\"}",
     "legendFormat": "{{feature}}"
    }
   ]
  },
  {
   "title": "Reference correlation",
   "type": "bargauge",
   "description": "Correlations between the feature and the target. It helps detects shifts in the relationship.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:num_target_drift:reference_correlations",
     "legendFormat": "{{feature}}"
    }
   ]
  },
  {
   "title": "Current correlations",
   "type": "bargauge",
   "description": "Correlations between the feature and the target. It helps detects shifts in the relationship.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:num_target_drift:current_correlations",
     "legendFormat": "{{feature}}"
    }
   ]
  }
 ]
}