services:
  provider:
    build: provider-service
    ports:
      - 8081:8081
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  consumer:
    build: consumer-service
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus.yaml
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    ports:
      - "9090:9090"

volumes:
  grafana-data: