server.port: 7004

spring.application.name: gateway-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

spring.cloud.gateway.routes:
  - id: bff-service
    uri: lb://bff-service
    predicates:
      - Path=/bff/**
  - id: user-service
    uri: lb://user-service
    predicates:
      - Path=/users/**
  - id: post-service
    uri: lb://post-service
    predicates:
      - Path=/posts/**
  - id: comment-service
    uri: lb://comment-service
    predicates:
      - Path=/comments/**

  - id: host_route_200
    uri: http://httpstat.us
    predicates:
      - Host=i.feel.lucky
      - Path=/headerrouting/**
    filters:
      - SetPath=/200
  - id: host_route_418
    uri: http://httpstat.us
    predicates:
      - Host=im.a.teapot
      - Path=/headerrouting/**
    filters:
      - SetPath=/418
  - id: host_route_501
    uri: http://httpstat.us
    predicates:
      - Path=/headerrouting/**
    filters:
      - SetPath=/501

---
spring.config.activate.on-profile: docker
server.port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

