services:
  eureka:
    build: eureka-service
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8761" ]
      interval: 10s
      timeout: 10s
      retries: 10

  traefik:
    image: traefik:v3.6
    container_name: traefik
    command:
      - "--api.insecure=true"                 # Dashboard accessibile senza auth (solo demo!)
      - "--api.dashboard=true"                # Abilita la dashboard
      - "--providers.docker=true"             # Auto-discovery dei container Docker
      - "--entrypoints.web.address=:80"       # Porta per il traffico HTTP
      - "--entrypoints.traefik.address=:8888" # Porta per dashboard/traefik
    ports:
      - "80:80"       # HTTP
      - "8888:8888"   # Dashboard / Traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"  # Per leggere container

  datetime-composite:
    build: datetime-composite-service
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - DATETIME_SERVICE_URL=http://traefik:80
    depends_on:
      eureka:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  datetime:
    build: datetime-service
    environment:
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    deploy:
      mode: replicated
      replicas: 3
    labels:
      - "traefik.enable=true"

      # Router 1: /date
      - "traefik.http.routers.date.rule=PathPrefix(`/date`)"
      - "traefik.http.routers.date.service=datetime"
      - "traefik.http.services.datetime.loadbalancer.server.port=8080"

      # Router 2: /time
      - "traefik.http.routers.time.rule=PathPrefix(`/time`)"
      - "traefik.http.routers.time.service=datetime"
    depends_on:
      eureka:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5